services:
  nodejs:
    image: plusquepro-image
    container_name: plusquepro-container
    build: .
    volumes:
      - .:/root/plusquepro
      - /root/plusquepro/node_modules
      - /root/plusquepro/.next
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
  db:
    image: mongo:6.0.15
    container_name: plusquepro-mongodb-container
    volumes:
      - "./mongo.setup.js:/docker-entrypoint-initdb.d/mongo.setup.js"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_APP_USERNAME: ${MONGO_APP_USERNAME}
      MONGO_APP_PASSWORD: ${MONGO_APP_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    networks:
      default:
        aliases:
          - plusquepro-database
